//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConvenienceStore.Model
{
    using System;
    using System.Collections.Generic;
    using System.Windows.Navigation;
    using ConvenienceStore.Model.Admin;
    using ConvenienceStore.ViewModel.StaffVM;

    public class Customer : BaseViewModel
    {
        #nullable enable

        public int _Id;
        public int Id { get { return _Id; } set { _Id = value; OnPropertyChanged(); } }
        private string? _Name;
        public string? Name { get { return _Name; } set { _Name = value; OnPropertyChanged(); } }
        private string? _Address;
        public string? Address { get { return _Address; } set { _Address = value; OnPropertyChanged(); } }
        private string? _Phone;
        public string? Phone { get { return _Phone; } set { _Phone = value; OnPropertyChanged(); } }
        private string? _Email;
        public string? Email { get { return _Email; } set { _Email = value; OnPropertyChanged(); } }
        private int? _Point;
        public int? Point { get { return _Point; } set { _Point = value; OnPropertyChanged(); } }

        #nullable disable
    }
}
