//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConvenienceStore.Model.Staff
{
    using ConvenienceStore.Model.Admin;
    using ConvenienceStore.ViewModel.StaffVM;
    using System;
    using System.Collections.Generic;

    public partial class BillDetail : BaseViewModel
    {
        public int BillId { get; set; }
        public string ProductId { get; set; }
        private Nullable<int> _Quantity;
        public Nullable<int> Quantity { get { return _Quantity; } set { _Quantity = value; OnPropertyChanged(); } }
        private Nullable<int> _TotalPrice;
        public Nullable<int> TotalPrice { get { return _TotalPrice; } set { _TotalPrice = value; OnPropertyChanged(); } }
    
        public virtual Bill Bill { get; set; }
        public virtual Product Product { get; set; }
    }
}
