//-----------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConvenienceStore.Model.Staff
{
    using ConvenienceStore.Utils.Helpers;
    using ConvenienceStore.ViewModel.StaffVM;
    using System;
    using System.Collections.Generic;
    public partial class Vouchers : BaseViewModel
    {
        #nullable enable

        private string? _ReleaseId;
        public string? ReleaseId { get => _ReleaseId; set { _ReleaseId = value; OnPropertyChanged(); } }
        private string? _ReleaseName;
        public string? ReleaseName { get => _ReleaseName; set { _ReleaseName = value; OnPropertyChanged(); } }
        private System.DateTime? _StartDate;
        public System.DateTime? StartDate { get => _StartDate; set { _StartDate = value; OnPropertyChanged(); } }
        private System.DateTime? _FinishDate;
        public System.DateTime? FinishDate { get => _FinishDate; set { _FinishDate = value; OnPropertyChanged(); } }
        private int? _ParValue; public int? ParValue { get => _ParValue; set { _ParValue = value; OnPropertyChanged(); } }
        private int? _Status; public int? Status { get => _Status; set { _Status = value; OnPropertyChanged(); } }
        public string? StatusStr
        {
            get
            {
                return Helpers.FormatStatus((Status == 1 ? true : false));
            }
        }
        private int? _Type; public int? Type { get => _Type; set { _Type = value; OnPropertyChanged(); } }

        #nullable disable
    }
}