//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConvenienceStore.Model.Staff
{
    using ConvenienceStore.Utils.Helpers;
    using ConvenienceStore.ViewModel.StaffVM;
    using System;
    using System.Collections.Generic;
    public partial class Vouchers : BaseViewModel
    {
        public int _Id { get; set; }
        public int Id { get => _Id; set { _Id = value; OnPropertyChanged(); } }
        public string _ReleaseId { get; set; }
        public string ReleaseId { get => _ReleaseId; set { _ReleaseId = value; OnPropertyChanged(); } }
        public string _ReleaseName; public string ReleaseName { get => _ReleaseName; set { _ReleaseName = value; OnPropertyChanged(); } }

        public Nullable<System.DateTime> _StartDate; public Nullable<System.DateTime> StartDate { get => _StartDate; set { _StartDate = value; OnPropertyChanged(); } }
        public Nullable<System.DateTime> _FinishDate; public Nullable<System.DateTime> FinishDate { get => _FinishDate; set { _FinishDate = value; OnPropertyChanged(); } }
        public Nullable<int> _ParValue; public Nullable<int> ParValue { get => _ParValue; set { _ParValue = value; OnPropertyChanged(); } }
        public bool _Status; public bool Status { get => _Status; set { _Status = value; OnPropertyChanged(); } }
        public string StatusStr
        {
            get
            {
                return Helpers.FormatStatus(Status);
            }
        }
    }
}